INSERT INTO DIRECCIONES (CALLE, CARRERA, NUMERO, LOCALIDAD, BARRIO)
VALUES
    ('Calle 80', 'Carrera 98', '50-00', 'Engativá', 'Santa Helenita'),
    ('Avenida Suba', 'Carrera 100', '30-01', 'Suba', 'Niza Norte'),
    ('Avenida Caracas', 'Carrera 13', '15-20', 'Chapinero', 'La Esmeralda'),
    ('Calle 100', 'Carrera 19', '45-60', 'Chapinero', 'El Chicó'),
    ('Avenida 68', 'Carrera 68', '80-00', 'Engativá', 'Normandía'),
    ('Avenida Ciudad de Cali', 'Carrera 86', '10-15', 'Kennedy', 'Patio Bonito'),
    ('Calle 26', 'Carrera 50', '20-50', 'Teusaquillo', 'Modelia'),
    ('Avenida Boyacá', 'Carrera 72', '45-50', 'Engativá', 'Boyacá Real'),
    ('Avenida Américas', 'Carrera 86', '5-15', 'Kennedy', 'Marsella'),
    ('Calle 6', 'Carrera 10', '10-25', 'Los Mártires', 'Santa Isabel'),
    ('Avenida NQS', 'Carrera 30', '45-20', 'Teusaquillo', 'La Soledad'),
    ('Calle 13', 'Carrera 85', '50-10', 'Fontibón', 'Villemar'),
    ('Avenida Caracas', 'Carrera 15', '35-00', 'Teusaquillo', 'La Soledad'),
    ('Calle 72', 'Carrera 15', '35-20', 'Chapinero', 'Chicó Norte'),
    ('Calle 53', 'Carrera 27', '14-30', 'Teusaquillo', 'Campín'),
    ('Avenida Primero de Mayo', 'Carrera 68', '5-30', 'Kennedy', 'Carvajal'),
    ('Calle 26', 'Carrera 10', '30-25', 'Los Mártires', 'La Alameda'),
    ('Avenida Caracas', 'Carrera 18', '20-30', 'Chapinero', 'El Lago'),
    ('Calle 19', 'Carrera 3', '5-15', 'Santa Fe', 'Las Aguas'),
    ('Avenida Boyacá', 'Carrera 72', '60-10', 'Engativá', 'Boyacá Real'),
    ('Calle 22', 'Carrera 10', '50-20', 'Los Mártires', 'La Estanzuela'),
    ('Avenida NQS', 'Carrera 30', '70-30', 'Teusaquillo', 'Granada'),
    ('Calle 26', 'Carrera 33', '80-15', 'Teusaquillo', 'Gaitán Cortés'),
    ('Calle 6', 'Carrera 15', '25-25', 'Santa Fe', 'Santa Bárbara'),
    ('Avenida Ciudad de Cali', 'Carrera 80', '90-00', 'Kennedy', 'Timiza'),
    ('Calle 80', 'Carrera 70', '50-00', 'Engativá', 'Las Ferias'),
    ('Calle 170', 'Carrera 7', '30-20', 'Usaquén', 'Cedritos'),
    ('Avenida Caracas', 'Carrera 20', '15-10', 'Chapinero', 'Quinta Camacho'),
    ('Calle 45', 'Carrera 10', '5-25', 'Teusaquillo', 'El Progreso'),
    ('Avenida Suba', 'Carrera 100', '20-25', 'Suba', 'Rincón del Chicó'),
    ('Calle 13', 'Carrera 50', '80-00', 'Fontibón', 'Zona Franca'),
    ('Avenida Américas', 'Carrera 50', '20-15', 'Kennedy', 'Ricaurte'),
    ('Calle 22', 'Carrera 50', '10-10', 'Los Mártires', 'Santa Fe'),
    ('Calle 72', 'Carrera 68', '30-20', 'Barrios Unidos', 'San Fernando'),
    ('Avenida Primero de Mayo', 'Carrera 68', '10-20', 'Kennedy', 'Carvajal'),
    ('Calle 80', 'Carrera 70', '30-30', 'Engativá', 'Las Ferias'),
    ('Calle 19', 'Carrera 7', '15-00', 'Santa Fe', 'Las Nieves'),
    ('Avenida Boyacá', 'Carrera 72', '70-20', 'Engativá', 'Normandía'),
    ('Calle 100', 'Carrera 15', '10-00', 'Chapinero', 'El Lago'),
    ('Calle 63', 'Carrera 30', '20-10', 'Teusaquillo', 'Quirigua'),
    ('Avenida Caracas', 'Carrera 18', '40-15', 'Chapinero', 'El Lago'),
    ('Calle 26', 'Carrera 13', '5-25', 'Teusaquillo', 'Los Alcázares'),
    ('Avenida Américas', 'Carrera 100', '10-20', 'Kennedy', 'Marsella'),
    ('Calle 53', 'Carrera 13', '15-20', 'Teusaquillo', 'Quirinal'),
    ('Calle 100', 'Carrera 19', '30-25', 'Chapinero', 'El Chicó'),
    ('Avenida Suba', 'Carrera 90', '50-20', 'Suba', 'Santa Bibiana'),
    ('Calle 80', 'Carrera 100', '70-10', 'Engativá', 'Niza Norte'),
    ('Avenida NQS', 'Carrera 30', '10-15', 'Teusaquillo', 'Teusaquillo'),
    ('Calle 6', 'Carrera 50', '30-30', 'Los Mártires', 'Eduardo Santos'),
    ('Calle 8', 'Carrera 50', '12-25', 'Los Mártires', 'San Andrés'),
    ('Avenida Primero de Mayo', 'Carrera 80', '15-10', 'Kennedy', 'Osorio'),
    ('Avenida Boyacá', 'Carrera 72', '90-00', 'Engativá', 'Normandía'),
    ('Calle 127', 'Carrera 15', '40-20', 'Usaquén', 'Santa Bibiana'),
    ('Calle 13', 'Carrera 100', '60-10', 'Fontibón', 'Fontibón Centro'),
    ('Avenida Caracas', 'Carrera 14', '80-15', 'Chapinero', 'Quinta Camacho'),
    ('Avenida NQS', 'Carrera 30', '15-20', 'Teusaquillo', 'Palermo'),
    ('Calle 26', 'Carrera 45', '10-15', 'Teusaquillo', 'Ciudad Universitaria'),
    ('Avenida Suba', 'Carrera 100', '5-10', 'Suba', 'Niza Norte'),
    ('Calle 63', 'Carrera 50', '25-20', 'Barrios Unidos', 'El Lago'),
    ('Calle 19', 'Carrera 5', '10-30', 'Santa Fe', 'Las Nieves'),
    ('Avenida Boyacá', 'Carrera 72', '10-20', 'Kennedy', 'Marsella'),
    ('Calle 53', 'Carrera 20', '45-10', 'Teusaquillo', 'El Campín'),
    ('Avenida Ciudad de Cali', 'Carrera 80', '30-25', 'Kennedy', 'Timiza'),
    ('Avenida Suba', 'Carrera 90', '5-10', 'Suba', 'Santa Bibiana'),
    ('Calle 80', 'Carrera 50', '15-00', 'Engativá', 'Las Ferias'),
    ('Avenida Caracas', 'Carrera 18', '10-25', 'Chapinero', 'El Lago'),
    ('Calle 45', 'Carrera 27', '30-30', 'Teusaquillo', 'El Campín'),
    ('Avenida NQS', 'Carrera 30', '20-30', 'Teusaquillo', 'Granada'),
    ('Calle 22', 'Carrera 10', '15-20', 'Los Mártires', 'La Estanzuela'),
    ('Avenida Américas', 'Carrera 50', '45-20', 'Kennedy', 'Ricaurte'),
    ('Calle 13', 'Carrera 86', '80-10', 'Fontibón', 'Fontibón Centro'),
    ('Avenida Primero de Mayo', 'Carrera 68', '10-00', 'Kennedy', 'Carvajal'),
    ('Calle 170', 'Carrera 15', '20-25', 'Usaquén', 'Cedritos'),
    ('Avenida Caracas', 'Carrera 13', '20-20', 'Teusaquillo', 'Chapinero'),
    ('Calle 19', 'Carrera 50', '10-15', 'Santa Fe', 'Las Aguas'),
    ('Avenida Boyacá', 'Carrera 72', '60-00', 'Engativá', 'Boyacá Real'),
    ('Calle 26', 'Carrera 33', '70-25', 'Teusaquillo', 'Gaitán Cortés'),
    ('Calle 6', 'Carrera 10', '15-25', 'Los Mártires', 'Santa Isabel'),
    ('Avenida Ciudad de Cali', 'Carrera 80', '25-25', 'Kennedy', 'Timiza'),
    ('Avenida NQS', 'Carrera 30', '5-15', 'Teusaquillo', 'Palermo'),
    ('Calle 53', 'Carrera 68', '30-25', 'Barrios Unidos', 'Santa Rosa'),
    ('Calle 80', 'Carrera 100', '5-10', 'Engativá', 'Niza Norte'),
    ('Avenida Suba', 'Carrera 90', '30-10', 'Suba', 'Rincón del Chicó'),
    ('Calle 22', 'Carrera 15', '15-10', 'Los Mártires', 'La Estanzuela'),
    ('Calle 100', 'Carrera 15', '15-00', 'Chapinero', 'El Chicó'),
    ('Calle 13', 'Carrera 100', '20-25', 'Fontibón', 'Fontibón Centro'),
    ('Avenida Américas', 'Carrera 80', '10-20', 'Kennedy', 'Marsella'),
    ('Calle 53', 'Carrera 50', '10-30', 'Barrios Unidos', 'El Lago'),
    ('Calle 19', 'Carrera 14', '10-00', 'Santa Fe', 'Las Nieves'),
    ('Calle 127', 'Carrera 15', '40-00', 'Usaquén', 'Santa Bibiana'),
    ('Avenida Boyacá', 'Carrera 72', '15-20', 'Kennedy', 'Marsella'),
    ('Calle 63', 'Carrera 30', '20-15', 'Teusaquillo', 'Quirigua'),
    ('Avenida Caracas', 'Carrera 20', '15-20', 'Chapinero', 'Quinta Camacho'),
    ('Calle 170', 'Carrera 7', '20-20', 'Usaquén', 'Cedritos'),
    ('Avenida Suba', 'Carrera 100', '40-25', 'Suba', 'Niza Norte'),
    ('Calle 6', 'Carrera 20', '30-10', 'Los Mártires', 'Santa Isabel'),
    ('Avenida NQS', 'Carrera 30', '10-30', 'Teusaquillo', 'Teusaquillo'),
    ('Avenida Caracas', 'Carrera 7', '1-50', 'Santa Fe', 'Centro Internacional'),
    ('Avenida Suba', 'Carrera 100', '85-20', 'Suba', 'Pontevedra'),
    ('Calle 80', 'Carrera 70', '60-30', 'Engativá', 'La Estrada'),
    ('Avenida Boyacá', 'Carrera 72', '50-50', 'Engativá', 'El Laurel'),
    ('Calle 19', 'Carrera 4', '20-10', 'Santa Fe', 'Las Aguas'),
    ('Calle 127', 'Carrera 19', '15-10', 'Usaquén', 'Santa Bibiana'),
    ('Calle 26', 'Carrera 68', '70-40', 'Teusaquillo', 'El Salitre'),
    ('Avenida 68', 'Carrera 68', '90-30', 'Engativá', 'La Granja'),
    ('Calle 53', 'Carrera 17', '60-15', 'Chapinero', 'Quinta Mutis'),
    ('Avenida NQS', 'Carrera 30', '25-35', 'Teusaquillo', 'Gaitán'),
    ('Calle 72', 'Carrera 11', '50-00', 'Chapinero', 'Rosales'),
    ('Avenida Primero de Mayo', 'Carrera 10', '80-20', 'Los Mártires', 'San Antonio'),
    ('Calle 22', 'Carrera 9', '40-20', 'Santa Fe', 'La Capuchina'),
    ('Calle 13', 'Carrera 20', '55-10', 'Santa Fe', 'Samper Mendoza'),
    ('Avenida Américas', 'Carrera 60', '65-30', 'Kennedy', 'Mandaly'),
    ('Calle 6', 'Carrera 40', '80-10', 'Teusaquillo', 'Paloquemao'),
    ('Calle 170', 'Carrera 9', '55-15', 'Usaquén', 'Toberín'),
    ('Calle 80', 'Carrera 68', '20-50', 'Engativá', 'Metrópolis'),
    ('Avenida Boyacá', 'Carrera 70', '15-10', 'Engativá', 'Santa Rosita'),
    ('Calle 127', 'Carrera 9', '50-20', 'Usaquén', 'Bella Suiza'),
    ('Calle 45', 'Carrera 13', '80-25', 'Teusaquillo', 'La Magdalena'),
    ('Avenida Caracas', 'Carrera 18', '20-00', 'Teusaquillo', 'Galerías'),
    ('Calle 22', 'Carrera 7', '65-10', 'Santa Fe', 'Las Nieves'),
    ('Avenida Suba', 'Carrera 85', '60-15', 'Suba', 'Niza Norte'),
    ('Calle 170', 'Carrera 7', '45-00', 'Usaquén', 'El Codito'),
    ('Calle 100', 'Carrera 11', '20-30', 'Chapinero', 'La Cabrera'),
    ('Avenida Ciudad de Cali', 'Carrera 90', '45-10', 'Kennedy', 'Banderas'),
    ('Calle 26', 'Carrera 30', '60-15', 'Teusaquillo', 'Salitre Greco'),
    ('Calle 6', 'Carrera 50', '15-00', 'Los Mártires', 'Eduardo Santos'),
    ('Avenida Caracas', 'Carrera 15', '70-20', 'Chapinero', 'Chapinero Central'),
    ('Calle 19', 'Carrera 50', '70-10', 'Santa Fe', 'Candelaria'),
    ('Avenida 68', 'Carrera 70', '10-00', 'Engativá', 'Minuto de Dios'),
    ('Calle 100', 'Carrera 15', '55-15', 'Chapinero', 'Rincón del Chicó'),
    ('Calle 45', 'Carrera 27', '35-20', 'Teusaquillo', 'Restrepo'),
    ('Calle 80', 'Carrera 60', '45-50', 'Engativá', 'Santa Mónica'),
    ('Avenida Boyacá', 'Carrera 72', '30-25', 'Engativá', 'Boyacá Real'),
    ('Calle 13', 'Carrera 40', '15-30', 'Los Mártires', 'San Cristóbal'),
    ('Avenida Suba', 'Carrera 85', '40-30', 'Suba', 'Pontevedra'),
    ('Avenida Primero de Mayo', 'Carrera 68', '15-15', 'Kennedy', 'Techo'),
    ('Calle 26', 'Carrera 13', '70-20', 'Teusaquillo', 'Ciudad Salitre'),
    ('Avenida Ciudad de Cali', 'Carrera 86', '40-10', 'Kennedy', 'Marsella'),
    ('Calle 100', 'Carrera 15', '80-30', 'Chapinero', 'Los Rosales'),
    ('Calle 127', 'Carrera 9', '65-10', 'Usaquén', 'Santa Bibiana'),
    ('Avenida Caracas', 'Carrera 15', '45-25', 'Teusaquillo', 'Chapinero Central'),
    ('Calle 170', 'Carrera 9', '10-25', 'Usaquén', 'San Cristóbal Norte');
